### ISSUE TITLE
[PE-D] Typo in output for help view

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-1/tp#154] opened 2021-10-30 18:09 UTC
![patienttypo.PNG](https://raw.githubusercontent.com/Herrekt/ped/main/files/3ae32237-69d7-422f-8a5a-920a55d17b6f.PNG)

Would it be better for it to be "patient's" instead of "patient?s".
The same issue is seen in staff.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Herrekt/ped#5

**Comment by Kureans** [comment] 2021-10-31 15:05
Duplicate of #129

**Closed by Kureans** 2021-10-31 15:05 UTC
