### ISSUE TITLE
[PE-D] List no. can keep increasing.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-1/tp#141] opened 2021-10-30 15:18 UTC
![listnomoveup.PNG](https://raw.githubusercontent.com/Herrekt/ped/main/files/fff25870-5503-4346-8cda-f673a74c541d.PNG)

Deleting the patients, especially the earlier ones does not seem to flush the patient's ID back up. Might become problematic when dealing in large scale of patients or staff as the list will keep ever increasing

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Herrekt/ped#1

**Comment by jushg** [comment] 2021-11-01 12:19
duplicate of #131

**Closed by jushg** 2021-11-01 12:19 UTC
Labels: type.Bug
